### ISSUE TITLE
friendly edit suggestion to update README to indicate license type by name

### ISSUE THREAD

**Issue by timoteostewart** [Osmerion/OneTrickPony#2]
[https://github.com/timoteostewart/OneTrickPony/commit/2d910310a11634b4c165d1759b1feeaa27b2b162](https://github.com/timoteostewart/OneTrickPony/commit/2d910310a11634b4c165d1759b1feeaa27b2b162)

**Comment by TheMrMilchmann** [comment]
Thank you for the suggestion. I've slightly tweaked the wording and applied it in 0380fe84d28f4297462a6b614eb2dae46b938991.

Also, note that the license was already detected correctly by GitHub, and information was added to the UI in at least two places before this change.
It's on the sidebar:
![image](https://user-images.githubusercontent.com/4029915/218253414-9f3fdef7-4eda-44a6-80ec-cce06d2301d5.png)

And visible when viewing the `LICENSE` file:
![image](https://user-images.githubusercontent.com/4029915/218253443-1b966a40-9698-4f1f-a6fe-67e26e245b83.png)
